/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file test_trilu_tiling.cpp
 * \brief Tiling UT for trilu operator
 */

#include "conversion/triu/op_host/arch35/triu_tiling.h"
#include <gtest/gtest.h>
#include <iostream>
#include "tiling_context_faker.h"
#include "tiling_case_executor.h"

using namespace std;
using namespace Ops::Math;

class TriluTiling : public testing::Test {
protected:
    static void SetUpTestCase() { std::cout << "TriluTiling SetUp" << std::endl; }

    static void TearDownTestCase() { std::cout << "TriluTiling TearDown" << std::endl; }
};

// float32, upper=1, diagonal=0, shape=(4,4)
TEST_F(TriluTiling, trilu_float32)
{
    optiling::TriluCompileInfo compileInfo = {64, 245760};
    std::vector<gert::TilingContextPara::OpAttr> attrs;
    attrs.emplace_back("upper", AnyValue::CreateFrom<int64_t>(int64_t(1)));

    gert::TilingContextPara tilingContextPara("Trilu",
                                              {
                                                  {{{4, 4}, {4, 4}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                              },
                                              {
                                                  {{{4, 4}, {4, 4}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                              },
                                              attrs, &compileInfo);
    uint64_t expectTilingKey = 134;
    string expectTilingData = "59392 16 1 1 0 1 1 1 36079 0 0 0 ";
    std::vector<size_t> expectWorkspaces = {16777216};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_SUCCESS, expectTilingKey, expectTilingData, expectWorkspaces);
}

// float16, upper=0, diagonal=0, shape=(4,4)
TEST_F(TriluTiling, trilu_float16)
{
    optiling::TriluCompileInfo compileInfo = {64, 245760};
    std::vector<gert::TilingContextPara::OpAttr> attrs;
    attrs.emplace_back("upper", AnyValue::CreateFrom<int64_t>(int64_t(0)));

    gert::TilingContextPara tilingContextPara("Trilu",
                                              {
                                                  {{{4, 4}, {4, 4}}, ge::DT_FLOAT16, ge::FORMAT_ND},
                                              },
                                              {
                                                  {{{4, 4}, {4, 4}}, ge::DT_FLOAT16, ge::FORMAT_ND},
                                              },
                                              attrs, &compileInfo);
    uint64_t expectTilingKey = 32;
    string expectTilingData = "59392 16 1 1 0 1 1 1 63281 0 0 0 ";
    std::vector<size_t> expectWorkspaces = {16777216};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_SUCCESS, expectTilingKey, expectTilingData, expectWorkspaces);
}
